config/routes.rb
Rails.application.routes.draw do
  resources :help_groups
  devise_for :users
  resources :appointments
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :specialist, class_name: 'User'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User'
end

app/models/help_group.rb
class HelpGroup < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy!

    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:status, :date)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/help_groups_controller.rb
class HelpGroupsController < ApplicationController
  before_action :set_help_group, only: %i[ show edit update destroy ]

  # GET /help_groups or /help_groups.json
  def index
    @help_groups = HelpGroup.all
  end

  # GET /help_groups/1 or /help_groups/1.json
  def show
  end

  # GET /help_groups/new
  def new
    @help_group = HelpGroup.new
  end

  # GET /help_groups/1/edit
  def edit
  end

  # POST /help_groups or /help_groups.json
  def create
    @help_group = HelpGroup.new(help_group_params)

    respond_to do |format|
      if @help_group.save
        format.html { redirect_to help_group_url(@help_group), notice: "Help group was successfully created." }
        format.json { render :show, status: :created, location: @help_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @help_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /help_groups/1 or /help_groups/1.json
  def update
    respond_to do |format|
      if @help_group.update(help_group_params)
        format.html { redirect_to help_group_url(@help_group), notice: "Help group was successfully updated." }
        format.json { render :show, status: :ok, location: @help_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @help_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /help_groups/1 or /help_groups/1.json
  def destroy
    @help_group.destroy!

    respond_to do |format|
      format.html { redirect_to help_groups_url, notice: "Help group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_help_group
      @help_group = HelpGroup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def help_group_params
      params.require(:help_group).permit(:topic)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/help_groups_helper.rb
module HelpGroupsHelper
end

app/views/appointments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@appointment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :status
    = f.input :date

  .form-actions
    = f.button :submit

app/views/appointments/edit.html.haml
%h1 Editing appointment

= render 'form'

= link_to 'Show', @appointment
\|
= link_to 'Back', appointments_path

app/views/appointments/index.html.haml
%h1 Listing appointments

%table
  %thead
    %tr
      %th Status
      %th Date
      %th
      %th
      %th

  %tbody
    - @appointments.each do |appointment|
      %tr
        %td= appointment.status
        %td= appointment.date
        %td= link_to 'Show', appointment
        %td= link_to 'Edit', edit_appointment_path(appointment)
        %td= link_to 'Destroy', appointment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Appointment', new_appointment_path

app/views/appointments/new.html.haml
%h1 New appointment

= render 'form'

= link_to 'Back', appointments_path

app/views/appointments/show.html.haml
%p#notice= notice

%p
  %b Status:
  = @appointment.status
%p
  %b Date:
  = @appointment.date

= link_to 'Edit', edit_appointment_path(@appointment)
\|
= link_to 'Back', appointments_path

app/views/articles/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@article) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :body

  .form-actions
    = f.button :submit

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles

%table
  %thead
    %tr
      %th Title
      %th Body
      %th
      %th
      %th

  %tbody
    - @articles.each do |article|
      %tr
        %td= article.title
        %td= article.body
        %td= link_to 'Show', article
        %td= link_to 'Edit', edit_article_path(article)
        %td= link_to 'Destroy', article, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @article.title
%p
  %b Body:
  = @article.body

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path

app/views/help_groups/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@help_group) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :topic

  .form-actions
    = f.button :submit

app/views/help_groups/edit.html.haml
%h1 Editing help_group

= render 'form'

= link_to 'Show', @help_group
\|
= link_to 'Back', help_groups_path

app/views/help_groups/index.html.haml
%h1 Listing help_groups

%table
  %thead
    %tr
      %th Topic
      %th
      %th
      %th

  %tbody
    - @help_groups.each do |help_group|
      %tr
        %td= help_group.topic
        %td= link_to 'Show', help_group
        %td= link_to 'Edit', edit_help_group_path(help_group)
        %td= link_to 'Destroy', help_group, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Help group', new_help_group_path

app/views/help_groups/new.html.haml
%h1 New help_group

= render 'form'

= link_to 'Back', help_groups_path

app/views/help_groups/show.html.haml
%p#notice= notice

%p
  %b Topic:
  = @help_group.topic

= link_to 'Edit', edit_help_group_path(@help_group)
\|
= link_to 'Back', help_groups_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InternMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
    <%= yield %>
  </body>
</html>